name: Go Test
on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
      
      - name: Install dependencies
        run: go mod download
      
      - name: Test
        run: go test -v -cover ./...
