name: GoLint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: false

      - name: golangci-lint-root
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.0
          args: --timeout 3m --config .golangci.yaml

      - name: golangci-lint-v2
        run: golangci-lint run --timeout 3m --config .golangci.yaml
        working-directory: v2